### ISSUE TITLE
Update to work with Godot 4

### ISSUE THREAD

**Issue by Yu-jinKim** [KoBeWi/Godot-Slider-Label#1]
Some stuff at the export level is broken, I'm new to GDScript and I never used Godot 3 so it might take some time for me to fix

**Comment by KoBeWi** [comment]
But the plugin was updated and works with Godot 4.

**Comment by Yu-jinKim** [comment]
My bad the files from the asset library are still on 3.4 though.
Cloning the Github and using those files works

**Comment by KoBeWi** [comment]
Yes, the old version is still available in Godot 3, but it's no longer updated.
Using the newest Godot version you can find the updated plugin, which works with Godot 4 and later. AssetLib will automatically pick correct version.
